### ISSUE TITLE
[Feature] Use Automade server.properties instead of Waiting for server jar to gen them

### ISSUE THREAD

**Issue by Doty1154** [DoubleDoorDevelopment/D3Backend#13]
When i setup a server the first time while waiting for it to upload. I could not edit the server.properties under the url that it provides. And then when the server finally started i could edit all the options when the server ran.
There were only 4 or so options to edit per server gen
And then the normal 15 or so.

**Comment by Claycorp** [comment]
Works like that intentionally. 
Mods can edit options inside the file thus they must be generated.

**Comment by Doty1154** [comment]
But theres not one mod that edit Server.properties :V and also they can edit it later after its genned also :V

**Comment by Claycorp** [comment]
Never said there was a mod that edits it. It CAN be edited by mods.
Thus why its generated when it is.

**Comment by dries007** [comment]
Yes, but it doesn't make sense to make a bunch of hardcoded values that may
or may not be generated, depending on what kind of server it is. I can
however add a thing to add properties manually. (And give you a list of
default options perhaps)
