### ISSUE TITLE
Modpack upload doesn't follow redirects

### ISSUE THREAD

**Issue by AaronAsAChimp** [DoubleDoorDevelopment/D3Backend#26]
When entering a url to upload a modpack, the application doesn't follow redirects and will error out with the message 'undefined'.

For example This URL:
https://minecraft.curseforge.com/projects/project-ozone-2-reloaded/files/2388314/download

Redirects to:
https://addons-origin.cursecdn.com/files/2388/314/Project_Ozone_2-Server-v.2.2.7.zip

**Comment by dries007** [comment]
yes, this is a known issue. The next update will have the new and improved Curse pack downloader, which fixes this issue and a bunch of other things, including it not downloading archived mods, updating servers without having to delete folders by hand etc...
